server:
  servlet:
    context-path: /grandchild-service
  port: 8082

spring:
  application:
    name: "grandchild"
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
  tracing:
    sampling:
      probability: 1.0
      endpoint: http://localhost:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: health
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://localhost:4318/v1/traces
#  metrics:
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true
